### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by cykevii** [belieb/HabboFlashLinux#1]

**Comment by belieb** [comment]
Thanks for letting me know. Does the script finish? What part of the installation fails for you? Are you using a Chromebook or Linux?

Script still works here on my two Chromebooks. On Linux you might need to install the appropriate Wine version manually before running the script. I recently changed the script to always use Wine 6.0.0. Be sure not to use 6.0.1 or higher since it breaks the client.
